name: Run Sushi Chef Illustrative Mathematics

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache folders and files
        uses: actions/cache@v4
        with:
          path: |
            restore/
            .ricecookerfilecache/
            storage/
            illustrativemath_cache.*
          key: resourcecache
          restore-keys: |
            resourcecache

      - name: Run main.py
        env:
          STUDIO_TOKEN: ${{ secrets.LE_STUDIO_TOKEN }}
          ILLUSTRATIVE_API_KEY: ${{ secrets.ILLUSTRATIVE_MATH_API_KEY }}
        run: python main.py
      - name: Always save cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            restore/
            .ricecookerfilecache/
            storage/
            illustrativemath_cache.*
          key: resourcecache
